import {pets,smoothies,food,type Round} from './data/adventures';
import {readClass,beginClass,recordVoice,fairQueue,parseNames,validNames,demoNames,escapeHtml as esc} from './class-session';
import {petArt,rescueScene} from './rescue-scene';
import './rescue.css';
import './smoothie.css';

const isPet=document.body.dataset.game==='rescue';
const title=isPet?'Super Pets Rescue':'Crazy Smoothie Lab';
const allCards=isPet?pets:smoothies;
const app=document.querySelector<HTMLDivElement>('#adventure')!;
type Phase='setup'|'play'|'reward'|'end';
let phase:Phase='setup',cards:Round[]=[],round=0,voice=0,names:string[]=[],queue:number[]=[],counts:number[]=[],recorded=new Set<number>();
let remaining=300,total=300,energy=4,paused=false,muted=false,calm=matchMedia('(prefers-reduced-motion: reduce)').matches;
let choice='',words:string[]=[],hint=false,reference=false,memoryShown=true,feedback='',outcome='',rewardLeft=0,lockUntil=0,last=performance.now();
let recipeIngredient='',excludedIngredient='';
let audio:AudioContext|undefined;
function ingredientMode(c:Round){return c.selectionModes?.[voice]||'none';}
let lifeLossUntil=0;
let selectionResult:''|'correct'|'wrong'='',selectionDelay=0;
function autoSelection(){return isPet&&phase==='play'&&!!roundCard().correctSelections;}
function optionsFor(c:Round){return voice===1&&c.secondOptions?c.secondOptions:c.options;}
function optionButtons(c:Round){const options=optionsFor(c);if(!options)return '';return `<div class="choices">${options.map(o=>{const result=choice===o.value?selectionResult:'';return b(`${o.icon?`<span>${isPet?petArt(o.value==='Leo'?'cat':o.value==='Turbo'?'turtle':o.value==='Coco'?'parrot':'dog'):o.icon}</span>`:''}${esc(o.label)}${result?`<small class="option-result">${result==='correct'?'✓ Correcto':'✕ Incorrecto'}</small>`:''}`,'choose:'+o.value,`${choice===o.value?'selected':''} ${result?'answer-'+result:''}`,selectionDelay>0);}).join('')}</div>`;}
const b=(label:string,act:string,cls='',disabled=false)=>`<button type="button" data-act="${esc(act)}" class="${cls}" ${disabled?'disabled':''}>${label}</button>`;
const time=()=>`${Math.floor(Math.ceil(remaining)/60)}:${String(Math.ceil(remaining)%60).padStart(2,'0')}`;
function clockLabel(){return remaining<=30?'¡QUEDAN 30 SEGUNDOS!':remaining<=60?'ÚLTIMO MINUTO':'TIEMPO RESTANTE';}
function shield(){return '<svg viewBox="0 0 48 58" aria-hidden="true"><path class="shield-left" d="M24 3 4 11v17q0 16 20 27V3Z"/><path class="shield-right" d="m24 3 20 8v17q0 16-20 27V3Z"/><path class="shield-shine" d="m12 17 12-5M12 24v6"/><path class="shield-crack" d="m25 5-6 15 12 6-13 14 7 12"/></svg>';}
function rescuePressure(){const ratio=Math.max(0,Math.min(100,remaining/total*100));return `<div class="pressure-panel"><div class="timer mission-timer ${remaining<=60?'warning':''} ${remaining<=30?'urgent':''}" role="timer" aria-label="Tiempo restante"><small id="clock-label">${clockLabel()}</small><b id="timer">${time()}</b><div class="time-track" role="progressbar" aria-label="Tiempo disponible" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(ratio)}"><span style="transform:scaleX(${ratio/100})"></span></div></div><div class="team-lives ${energy===1?'last-life':''}"><div class="lives-title"><span>VIDAS DEL EQUIPO</span><b>${energy}<small>/4</small></b></div><div class="shields" aria-label="${energy} de 4 vidas">${Array.from({length:4},(_,i)=>`<i class="life-shield ${i<energy?'on':'lost'} ${i===energy&&performance.now()<lifeLossUntil?'just-lost':''}">${shield()}</i>`).join('')}</div><small class="lives-message">${energy===0?'SIN VIDAS':energy===1?'¡ÚLTIMA OPORTUNIDAD!':'JUNTOS HASTA EL FINAL'}</small></div>${performance.now()<lifeLossUntil?`<div class="life-loss" role="status"><b>−1 VIDA</b><span>${energy>0?'¡Equipo, aún podemos lograrlo!':'La misión necesita otro intento.'}</span></div>`:''}</div>`;}
function updateClock(){app.querySelector('#timer')!.textContent=time();app.querySelector('.timer')?.classList.toggle('urgent',remaining<=30);{app.querySelector('.mission-timer')?.classList.toggle('warning',remaining<=60);const label=app.querySelector('#clock-label');if(label)label.textContent=clockLabel();const bar=app.querySelector<HTMLElement>('.time-track span');if(bar)bar.style.transform=`scaleX(${Math.max(0,remaining/total)})`;app.querySelector('.time-track')?.setAttribute('aria-valuenow',String(Math.round(remaining/total*100)));}}
function rescueStage(c:Round,complete=false){
 const instruction=c.kind==='repair'?'FIX THE BRIDGE':c.kind==='translate'?'DECODE THE MESSAGE':c.kind==='memory'?'RESTORE THE SIGNAL':c.kind==='build'?'BUILD THE PATH':c.kind==='personal'?'BRING THE TEAM HOME':'CHOOSE YOUR HERO';
 return `<main class="rescue-stage kind-${c.kind} ${complete?'rescued':''} ${energy===1?'danger':''}">${rescueScene(c,voice,complete)}<div class="rescue-stage-top"><div><span>RESCUE ${complete?round:round+1} / ${cards.length}</span><h2>${esc(c.title)}</h2></div></div>${complete?`<section class="rescue-success"><span>PATH UNLOCKED</span><h1>¡Rescate logrado!</h1><p>Dos voces. Un equipo a salvo.</p></section>`:`<section class="challenge rescue-challenge"><div class="round-label">${instruction}</div>${interaction(c)}</section>`}<div class="rescue-route">${cards.map((_,i)=>`<span class="${i<round?'done':i===round?'current':''}">${i<round?'✓':i+1}</span>`).join('')}</div><div class="rescue-feedback" role="status">${esc(complete?'¡Mira cómo cruza tu héroe!':feedback|| (voice===0?'Una voz abre el camino. La segunda completa el rescate.':'¡El camino responde! Segunda voz: termina el rescate.'))}</div></main>`;
}
function rescuePlay(){const id=queue[round*2+voice],next=queue[round*2+1],c=roundCard();return `<div class="speaker"><span>🎤 <strong>${esc(names[id])}</strong> · voz ${voice+1}/2</span><small>${voice===0?'Después: '+esc(names[next]):'Completa el rescate'}</small></div>${rescueStage(c)}<footer class="coach-bar"><small>COACH · ${counts.filter(n=>n>0).length}/${names.length} hablaron aquí</small><div>${autoSelection()?'':b('✓ Correcto','correct','correct',c.kind==='memory'&&memoryShown)}${b('🤝 Con ayuda','help','help',c.kind==='memory'&&memoryShown)}${autoSelection()?'':b('↻ Incorrecto','wrong','wrong',c.kind==='memory'&&memoryShown)}${b('💡 Pista','hint')}${b('•••','pause','icon')}</div></footer>`;}
function tone(type:'good'|'bad'|'win'|'tap'){
 if(muted)return;try{audio??=new AudioContext();void audio.resume();const notes=type==='win'?[523,659,784,1047]:type==='good'?[523,784]:type==='bad'?[196,147]:[440];
 notes.forEach((f,i)=>{const o=audio!.createOscillator(),g=audio!.createGain(),t=audio!.currentTime+i*.12;o.frequency.value=f;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.08,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(audio!.destination);o.start(t);o.stop(t+.25);});}catch{}
}
function header(){return `<header class="top"><img class="logo" src="/missions/v1/assets/english4kids-logo.png" alt="English4Kids"><div class="brand"><strong>${isPet?'🐾':'🥤'} ${title}</strong><small>L2 · W4 · D1 · REPASO ${isPet?'SEMANA 3':'SEMANA 1'} · VISTA PREVIA</small></div><div class="mission-score">${phase==='setup'?'MISIÓN COOPERATIVA':`${round} / ${cards.length} ${isPet?'rescates':'pedidos'}`}</div>${phase!=='setup'?rescuePressure():`<div class="timer ${remaining<=30?'urgent':''}" role="timer" aria-label="Tiempo restante"><small>TIEMPO RESTANTE</small><b id="timer">${time()}</b></div>`}${b(muted?'🔇':'♫','mute','icon')} ${b('⛶','fullscreen','icon')}${phase==='play'||phase==='reward'?b('Ⅱ','pause','icon'):''}</header>`;}
function setup(){const s=readClass();return `<main class="prepare"><section class="welcome"><p class="eyebrow">${isPet?'CHOOSE A HERO. SAVE THE TEAM.':'CHOOSE. SPEAK. BLEND.'}</p><div class="welcome-art">${isPet?petArt('dog')+petArt('cat')+petArt('turtle'):'🍓 🥭 🍇'}</div><h1>${isPet?'Small heroes.<br><em>Big rescue.</em>':'Your words.<br><em>Wild recipes.</em>'}</h1><p>${isPet?'Hay mascotas esperando al otro lado del bosque. Usa sus acciones para abrir el camino.':'El laboratorio está por abrir. Escucha los pedidos, elige ingredientes y prepara las mezclas.'}</p><a href="/missions/v1/day.html">← Las tres misiones del día</a></section><form id="prepare" class="prepare-form"><h2>Prepara la misión</h2><label for="names">8–13 participantes, separados por comas</label><textarea id="names" placeholder="Ana, Luis, Sofía…">${esc(s.names.join(', '))}</textarea><small>${s.names.length?'Conservamos la participación de los otros juegos.':'Vacío: 10 exploradores para probar.'} Quienes menos hablaron empiezan.</small><div class="time-fields"><div><label for="minutes">Duración</label><select id="minutes">${[3,5,8,10,12,15].map(n=>`<option value="${n}" ${n===(s.minutes||5)?'selected':''}>${n} minutos</option>`).join('')}<option value="custom" ${![3,5,8,10,12,15].includes(s.minutes)?'selected':''}>Personalizada</option></select></div><div><label for="custom">Minutos personalizados</label><input type="number" id="custom" min="2" max="20" value="${s.minutes||5}"></div></div><p class="length-note" id="length-note"></p><label class="check"><input id="calm" type="checkbox" ${calm?'checked':''}> Reducir movimiento</label><div class="rules">${isPet?'4 vidas del equipo. Incorrecto: −1 vida y reintenta.':'4 oportunidades para mantener abierto el laboratorio. Incorrecto: −1 y reintenta.'}<br>Con ayuda: −5 segundos y avanza. Dos voces completan cada ${isPet?'rescate':'pedido'}.<br>${isPet?'Las opciones con respuesta definida se califican al pulsarlas. El coach valida los retos orales.':'El coach valida la respuesta oral; seleccionar no da puntos.'}</div><p id="error" role="alert"></p>${b(isPet?'Iniciar el rescate →':'Abrir el laboratorio →','start','primary')}</form></main>`;}
function lab(c:Round){const selected=food[recipeIngredient],excluded=food[excludedIngredient];return `<div class="lab ${phase==='reward'?'blending':''}"><div class="lab-sign">${phase==='reward'?'ORDER READY!':'SMOOTHIE STATION'}</div><div class="lab-shelves"><span>🍇</span><span>🍓</span><span>🥭</span></div><div class="blender"><div class="blender-lid"></div><div class="blender-jar"><div class="liquid" style="--juice:${selected?.color||'#c997f9'};height:${phase==='reward'?'85%':selected?'58%':'15%'}"><i></i><i></i><i></i></div><div class="floating-fruit">${selected?.icon||'✦'}</div><div class="jar-lines">―<br>―<br>―</div></div><div class="blender-base"><span></span><b>E4K</b></div></div><div class="recipe-status"><span>EN LA MEZCLA</span><strong>${selected?`${selected.icon} ${esc(selected.label)}`:"Elige qué agregar"}</strong></div>${excluded?`<div class="excluded-ingredient" role="status"><span>FUERA DE LA MEZCLA</span><strong>⊘ ${excluded.icon} ${esc(excluded.label)}</strong></div>`:""}<div class="counter-top"></div><div class="served">${cards.map((_,i)=>`<span class="${i<round?'done':''}">${i<round?'🥤':'○'}</span>`).join('')}</div></div>`;}
function roundCard(){return cards[Math.min(round,cards.length-1)]!;}
function interaction(c:Round){if(c.kind==='memory'&&memoryShown)return `<div class="memory-card"><small>${isPet?"LOOK & REMEMBER":"TU TARJETA DE CLIENTE · LOOK & REMEMBER"}</small><p>${esc(c.memory!)}</p>${b('Ocultar y recordar','hide','primary')}</div>`;
 return `${!isPet&&c.order&&c.kind!=='memory'&&c.kind!=='repair'?`<div class="order"><span>💬 ${esc(c.orderLabel||'TU TARJETA DE CLIENTE')}</span><p>${esc(c.order)}</p></div>`:''}<h2 class="challenge-prompt">${esc(!isPet&&c.kind==='repair'&&voice===0?'I likes grapes.':voice===0?c.prompt:c.second)}</h2>${optionButtons(c)}${c.ingredients&&ingredientMode(c)!=='none'?`<div class="ingredient-action ${ingredientMode(c)}">${ingredientMode(c)==='exclude'?'⊘ DEJAR FUERA DE LA MEZCLA':'+ AGREGAR A LA MEZCLA'}</div><div class="ingredients ${ingredientMode(c)}">${c.ingredients.map(id=>b(`<span>${food[id].icon}</span>${food[id].label}`,'choose:'+id,choice===id?'selected':'')).join('')}</div>`:''}${c.words?`<div class="sentence">${esc(words.join(' '))||'Ordena el mensaje…'}</div><div class="word-bank">${c.words.filter(w=>!words.includes(w)).map(w=>b(esc(w),'word:'+w)).join('')}${b('↺','resetwords','icon')}</div>`:''}<p class="oral-note">${!isPet?'Tú eres el cliente. El coach escucha y valida tu respuesta.':autoSelection()?'Coach: pulsa la opción que diga el estudiante. Se califica automáticamente.':voice===0?'Selecciona si hace falta y responde en voz alta.':'Segunda voz: completa la misión hablando.'}</p>${hint?`<div class="hint">💡 ${esc(c.hint)}</div>`:''}${reference?`<div class="hint">Referencia del coach: ${esc(c.answers[voice])}</div>`:''}`;}
function smoothieStage(c:Round,complete=false){
 const labels={choose:'CREATE YOUR RECIPE',repair:'REPAIR THE RECIPE',translate:'DECODE THE ORDER',memory:'REMEMBER THE RECIPE',build:'BUILD YOUR MESSAGE',personal:'MAKE IT YOURS'};
 return `<main class="smoothie-stage ${complete?'order-complete':''} ${voice===1?'machine-ready':''}"><div class="shop-awning" aria-hidden="true"></div><div class="shop-title"><span>THE SMOOTHIE LAB</span><small>${complete?'PEDIDO ENTREGADO':`PEDIDO ${round+1} DE ${cards.length}`}</small></div>${lab(c)}${complete?`<section class="delivery"><div class="hero-cup"><span>★</span></div><p>FRESHLY MADE</p><h1>¡Pedido listo!</h1><p>Dos voces. Una receta lograda.</p></section>`:`<section class="challenge recipe-ticket"><div class="round-label">${voice===1&&c.kind==='repair'?'ASK YOUR PARTNER':labels[c.kind]}</div>${interaction(c)}</section>`}<div class="station-response" role="status">${complete?'¡Una bebida más para la gran inauguración!':feedback||'Cada voz nos acerca a abrir el laboratorio.'}${!complete&&voice===1&&c.kind==='repair'?`<strong class="repaired-message">✓ ${esc(c.answers[0])}</strong>`:''}</div><div class="order-counter" aria-label="${round} de ${cards.length} pedidos entregados">${cards.map((_,i)=>`<div class="order-cup ${i<round?'filled':''} ${i===round?'current':''}"><i><b>★</b></i><span>${i<round?'✓':i+1}</span></div>`).join('')}<p>${round} / ${cards.length}<small>PARA INAUGURAR</small></p></div></main>`;
}
function play(){if(isPet)return rescuePlay();const c=roundCard(),id=queue[round*2+voice],next=queue[round*2+1];return `<div class="speaker"><span>🎤 <strong>${esc(names[id])}</strong> · voz ${voice+1}/2</span><small>${voice===0?'Después: '+esc(names[next]):'Completa este pedido'}</small></div>${smoothieStage(c)}<footer class="coach-bar"><small>COACH · ${counts.filter(n=>n>0).length}/${names.length} hablaron aquí</small><div>${b('✓ Correcto','correct','correct',c.kind==='memory'&&memoryShown)}${b('🤝 Con ayuda','help','help',c.kind==='memory'&&memoryShown)}${b('↻ Incorrecto','wrong','wrong',c.kind==='memory'&&memoryShown)}${b('💡 Pista','hint')}${b('•••','pause','icon')}</div></footer>`;}
function reward(){const c=cards[round-1];return isPet?rescueStage(c,true):`<div class="speaker"><strong>¡Buen trabajo, equipo!</strong></div>${smoothieStage(c,true)}`;}
function end(){const win=outcome==='win';return `<main class="finish ${win?'won':''}"><p class="eyebrow">${win?'MISSION COMPLETE':outcome==='timeout'?'TIME’S UP':outcome==='energy'?'MISSION FAILED':'MISIÓN TERMINADA'}</p><div class="final-art">${isPet?(win?['dog','cat','turtle','parrot'].map(petArt).join(''):petArt('dog')):(win?'<div class="open-sign">NOW OPEN<small>ENGLISH4KIDS SMOOTHIE LAB</small></div>':'🥤')}</div><h1>${win?(isPet?'Everybody is home!':'The lab is open!'):(isPet?'The team needs another try.':'Let’s try a new recipe.')}</h1><p>${win?(isPet?'Los héroes están juntos y a salvo. ¡Rescate completado!':'Pedidos entregados. ¡Gran inauguración del laboratorio!'):(outcome==='energy'?'Se agotaron las oportunidades.':'El tiempo de esta misión terminó.')}</p><div class="stats"><span><b>${round}/${cards.length}</b>${isPet?'rescates':'pedidos'}</span><span><b>${counts.filter(n=>n>0).length}/${names.length}</b>hablaron aquí</span><span><b>${readClass().spoken.filter(n=>n>0).length}/${names.length}</b>hablaron en la sesión</span></div><div class="finish-actions"><a class="primary button-link" href="/missions/v1/day.html">Elegir la siguiente misión →</a>${b('Jugar otra vez','restart')}</div>${win?'<div class="confetti" aria-hidden="true">'+Array.from({length:18},(_,i)=>`<i style="--x:${i*5.8}%;--delay:${i%4*.2}s">✦</i>`).join('')+'</div>':''}</main>`;}
function render(){document.body.dataset.phase=phase;document.body.dataset.calm=String(calm);document.body.dataset.paused=String(paused);app.innerHTML=header()+(phase==='setup'?setup():phase==='play'?play():phase==='reward'?reward():end())+(paused?`<div class="pause-overlay"><section><h2>Misión en pausa</h2><p>El reloj está detenido.</p>${b('Continuar','pause','primary')}${b('Ver respuesta de referencia','reference','',phase!=='play')}${b('Terminar misión','finish')}</section></div>`:'');
 app.querySelector('[data-act="mute"]')?.setAttribute('aria-label',muted?'Activar sonido':'Silenciar');app.querySelector('[data-act="fullscreen"]')?.setAttribute('aria-label','Pantalla completa');
 app.querySelectorAll('[data-act^="choose:"]').forEach(el=>el.setAttribute('aria-pressed',String(el.classList.contains('selected'))));
 if(selectionDelay>0)app.querySelectorAll<HTMLButtonElement>('[data-act]').forEach(el=>{if(!['pause','mute','fullscreen'].includes(el.dataset.act!))el.disabled=true;});
 if(phase==='setup')updateLength();
}
function selectedMinutes(){const select=app.querySelector<HTMLSelectElement>('#minutes')!;return select.value==='custom'?Number(app.querySelector<HTMLInputElement>('#custom')!.value):Number(select.value);}
function updateLength(){const n=selectedMinutes(),count=n<=3?3:n<=5?5:7;app.querySelector('#length-note')!.textContent=`${count} ${isPet?'rescates':'pedidos'} · ${count*2} turnos. La prioridad continúa en el siguiente juego.`;}
function resetCard(){selectionDelay=0;selectionResult='';voice=0;choice='';recipeIngredient=cards[round]?.recipe||'';excludedIngredient='';words=[];hint=reference=false;memoryShown=true;feedback='';}
function finish(reason:string){selectionDelay=0;selectionResult='';outcome=reason;phase='end';paused=false;tone(reason==='win'?'win':'bad');render();}
function markVoice(){const pos=round*2+voice;if(!recorded.has(pos)){recorded.add(pos);counts[queue[pos]]++;recordVoice(names[queue[pos]]);}}
function act(action:string,fromSelection=false){
 if(action==='mute'){muted=!muted;const el=app.querySelector('[data-act="mute"]')!;el.textContent=muted?'🔇':'♫';el.setAttribute('aria-label',muted?'Activar sonido':'Silenciar');return;}
 if(action==='fullscreen'){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});return;}
 if(action==='start'&&phase==='setup'){const input=parseNames(app.querySelector<HTMLTextAreaElement>('#names')!.value),minutes=selectedMinutes();if((input.length&&!validNames(input))||!Number.isFinite(minutes)||minutes<2||minutes>20){app.querySelector('#error')!.textContent='Usa 8–13 nombres distintos y una duración entre 2 y 20 minutos.';return;}
 names=input.length?input:demoNames();beginClass(names,minutes);const n=minutes<=3?3:minutes<=5?5:7;cards=allCards.slice(0,n);queue=fairQueue(names,n*2);counts=names.map(()=>0);recorded=new Set();round=0;energy=4;lifeLossUntil=0;remaining=total=minutes*60;paused=false;calm=app.querySelector<HTMLInputElement>('#calm')!.checked;resetCard();phase='play';last=performance.now();lockUntil=0;tone('tap');render();return;}
 if(action==='restart'&&phase==='end'){phase='setup';remaining=total;render();return;}
 if(phase==='setup'||phase==='end')return;
 if(action==='pause'){paused=!paused;last=performance.now();render();return;}
 if(paused){if(action==='finish')finish('early');else if(action==='reference'&&phase==='play'){reference=true;paused=false;render();}return;}
 if(phase!=='play'||selectionDelay>0)return;
 if(action==='hide'){memoryShown=false;render();return;}
 if(action==='hint'){hint=!hint;render();return;}
 if(action.startsWith('choose:')){const value=action.slice(7);if(isPet&&!optionsFor(roundCard())?.some(o=>o.value===value))return;if(autoSelection()&&performance.now()<lockUntil)return;if(!isPet){const c=roundCard(),mode=ingredientMode(c);if(mode==='none'||!c.ingredients?.includes(value))return;if(mode==='add'){recipeIngredient=value;if(excludedIngredient===value)excludedIngredient='';}else{excludedIngredient=value;if(recipeIngredient===value)recipeIngredient='';}}choice=value;if(autoSelection()){selectionResult=value===roundCard().correctSelections![voice]?'correct':'wrong';selectionDelay=.8;}else selectionResult='';tone('tap');render();return;}
 if(action.startsWith('word:')){const w=action.slice(5);if(!words.includes(w))words.push(w);render();return;}
 if(action==='resetwords'){words=[];render();return;}
 if(autoSelection()&&!fromSelection&&(action==='correct'||action==='wrong'))return;
 if(!['correct','help','wrong'].includes(action)||performance.now()<lockUntil||(roundCard().kind==='memory'&&memoryShown))return;
 lockUntil=performance.now()+650;markVoice();
 if(action==='wrong'){energy--;lifeLossUntil=performance.now()+1800;feedback='−1 '+(isPet?'vida':'oportunidad')+' · Intenten otra vez con apoyo del equipo.';tone('bad');if(energy===0)finish('energy');else{render();app.querySelector(isPet?'.rescue-stage':'.smoothie-stage')?.classList.add('hit');}return;}
 if(action==='help'){remaining=Math.max(0,remaining-5);if(!remaining){finish('timeout');return;}}
 feedback=action==='help'?'−5 s · ¡Respuesta lograda con ayuda!':'¡Mensaje recibido!';tone('good');hint=reference=false;
 if(voice===0){voice=1;choice='';selectionResult='';render();app.querySelector(isPet?'.rescue-stage':'.smoothie-stage')?.classList.add('step');}else{round++;phase='reward';rewardLeft=isPet?3.6:2.1;render();}
}
app.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-act]');if(el&&!el.disabled)act(el.dataset.act!);});
app.addEventListener('submit',e=>{e.preventDefault();act('start');});
app.addEventListener('change',e=>{if(phase==='setup'&&['minutes','custom'].includes((e.target as HTMLElement).id))updateLength();});
document.addEventListener('keydown',e=>{if(e.repeat||(e.target as HTMLElement).matches('input,textarea,select'))return;const a:Record<string,string>={c:'correct',h:'help',r:'wrong',p:'pause'};if(a[e.key.toLowerCase()]){e.preventDefault();act(a[e.key.toLowerCase()]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(phase==='play'||phase==='reward')&&!paused){paused=true;render();}});
setInterval(()=>{const now=performance.now(),delta=(now-last)/1000;last=now;if(lifeLossUntil&&now>=lifeLossUntil){lifeLossUntil=0;app.querySelector('.life-loss')?.remove();app.querySelector('.just-lost')?.classList.remove('just-lost');}if(paused||phase==='setup'||phase==='end')return;if(phase==='reward'){rewardLeft-=delta;if(rewardLeft<=0){if(round===cards.length)finish('win');else{resetCard();phase='play';render();}}return;}remaining=Math.max(0,remaining-delta);if(remaining===0){finish('timeout');return;}updateClock();if(selectionDelay>0){selectionDelay=Math.max(0,selectionDelay-delta);if(selectionDelay===0)act(selectionResult,true);}},100);
render();
