import {challenges} from './data/content';
const root=document.querySelector<HTMLDivElement>('#app')!;
let names:string[]=[],counts:number[]=[],queue:number[]=[],round=0,step=0,energy=4,seconds=600,paused=false,started=false,finished=false,showAnswer=false,hidden=false,selected=-1,words:string[]=[],feedback='',pending=false;
let credited:boolean[]=Array(14).fill(false);
function recordVoice(){const position=round*2+step;if(!credited[position]){counts[queue[position]!]!++;credited[position]=true;}}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,cls='')=>`<button class="${cls}" data-action="${action}">${label}</button>`;
const header=()=>`<header><a href="/">✦ SHAPE ISLAND</a><span class="preview">PROTOTIPO · S4 / D1</span><span class="right">Kids Super Intensive · Nivel 2</span></header>`;
function setup(){root.innerHTML=header()+`<main class="setup"><div class="intro"><p class="eyebrow">10 MINUTOS · UNA MISIÓN COMPARTIDA</p><h1>Every voice<br>builds the <em>bridge.</em></h1><p>La isla perdió su conexión. Recuperen siete señales para abrir el puente y volver a casa.</p><div class="tags"><span>7 retos diferentes</span><span>14 oportunidades de hablar</span><span>Sin IA</span></div><div class="setup-art">✦<span>🏝️</span>✦</div></div><section class="panel"><p class="eyebrow">PREPARAR LA EXPEDICIÓN</p><h2>¿Quiénes juegan hoy?</h2><label for="names">Nombres o apodos, separados por comas</label><textarea id="names" placeholder="Ana, Juan, Sofía, Luis…"></textarea><p class="muted">Pon primero a quienes menos hablaron. De 8 a 13 participantes. Si lo dejas vacío, usaremos 10 turnos numerados.</p><label for="duration">Duración de esta prueba</label><select id="duration"><option value="600">10 minutos</option><option value="480">8 minutos</option><option value="720">12 minutos</option></select><div class="note">Todos piensan. Dos estudiantes intervienen en cada reto. El coach confirma cada intervención; las opciones no dan puntos automáticamente.</div><p id="error" role="alert"></p>${button('Iniciar misión →','start','primary')}</section></main>`;}
function world(){return `<section class="world"><div class="world-title"><span>LIVE MISSION</span><b>${round}/7 señales</b></div><div class="island"><div class="stars">✦ · ✧ · ✦ · ✧</div><div class="gate ${finished&&round===7?'open':''}">🏝️</div><div class="bridge">${challenges.map((_,i)=>`<span class="${i<round?'built':''}">${i<round?'✦':i+1}</span>`).join('')}</div><div class="ship" style="left:${8+round*10}%">🚀</div></div><h2>${finished?round===7?'Connection restored!':'We can try again.':'Bring everyone home.'}</h2><p>${feedback||'Each voice carries the signal forward.'}</p><div class="energy"><span>Signal energy</span><b>${'●'.repeat(energy)}${'○'.repeat(4-energy)}</b></div><div class="progress"><i style="width:${round/7*100}%"></i></div></section>`;}
function picture(){const c=challenges[round]!;const paths:Record<string,string>={circle:'<circle cx="50" cy="50" r="40"/>',star:'<path d="M50 4 63 34 97 36 71 60 79 94 50 76 21 94 29 60 3 36 37 34Z"/>',triangle:'<path d="M50 7 95 92 5 92Z"/>',heart:'<path d="M50 91C-25 43 8-16 50 21 92-16 125 43 50 91Z"/>',square:'<rect x="10" y="10" width="80" height="80" rx="7"/>',oval:'<ellipse cx="50" cy="50" rx="46" ry="28"/>',rectangle:'<rect x="4" y="24" width="92" height="52" rx="6"/>'};return `<div class="pictures ${hidden?'hidden':''}" aria-label="${hidden?'Hidden picture':`${c.count} ${c.shape}`}">${hidden?'<span>?</span>':Array.from({length:c.count},()=>`<svg viewBox="0 0 100 100" fill="${c.color}">${paths[c.shape]}</svg>`).join('')}</div>`;}
function render(){if(!started)return setup();if(finished)return finale();const c=challenges[round]!,speaker=queue[round*2+step]!,next=queue[round*2+1]!;
root.innerHTML=header()+`<div class="toolbar"><span>THERE IS / THERE ARE · SHAPES</span><div><b id="clock">${time()}</b>${button(paused?'Continuar':'Pausa','pause')}${button('Terminar','finish')}</div></div><main class="stage">${world()}<section class="challenge panel"><p class="eyebrow">${round+1} / 7 · ${c.kind}</p><h1>${c.title}</h1>${picture()}<h2 class="prompt">${escape(c.prompt)}</h2>${c.options?`<div class="options">${c.options.map((o,i)=>button(`${String.fromCharCode(65+i)} · ${escape(o)}`,`option:${i}`,selected===i?'selected':'')).join('')}</div>`:''}${c.words?`<div class="assembled">${escape(words.join(' '))||'Your message goes here…'}</div><div class="words">${c.words.filter(w=>!words.includes(w)).map(w=>button(escape(w),'word:'+w)).join('')}${button('↺','reset')}</div>`:''}${c.kind==='REMEMBER'?button(hidden?'Mostrar imagen':'Ocultar imagen','hide'):''}<div class="speaker"><span>${step===0?'EXPLORER':'SIGNAL PARTNER'} · ${step+1}/2</span><strong>${escape(names[speaker]!)}</strong><p>${escape(step===0?c.lead:c.follow)}</p>${step===0?`<small>Después: ${escape(names[next]!)}</small>`:''}</div>${showAnswer?`<div class="answer">Referencia: ${escape(c.answers[step]!)}</div>`:''}<div class="controls">${button('✓ Habló y lo logró','success','primary')}${button('↻ Necesita otro intento','retry')}${button('Dar apoyo','answer')}${button('Reasignar turno','swap')}</div><p class="muted">El coach valida la intervención oral. Reintentar consume una unidad de energía; no elimina al estudiante.</p></section></main><details class="coach"><summary>Registro del coach · ${counts.filter(n=>n>0).length}/${names.length} participaron · no es un ranking</summary><div>${names.map((n,i)=>`<span>${escape(n)} <b>${counts[i]} ${counts[i]===1?'intervención':'intervenciones'}</b></span>`).join('')}</div></details>${paused?'<div class="pause"><h2>Misión en pausa</h2>'+button('Continuar','pause','primary')+'</div>':''}`;
root.querySelectorAll<HTMLButtonElement>('.challenge button').forEach(b=>b.disabled=paused||pending);}
function time(){return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function finale(){const won=round===7;root.innerHTML=header()+`<main class="finale"><p class="eyebrow">${won?'MISSION COMPLETE':'MISIÓN SIN COMPLETAR'}</p><div class="final-symbol">${won?'🏝️':'📡'}</div><h1>${won?'Every voice.<br>One great team.':'The island is waiting.'}</h1><p>${won?'El puente está conectado. La tripulación volvió a casa.':'Recuperen la señal y vuelvan a intentarlo.'}</p><div class="stats"><span><b>${round}/7</b> señales</span><span><b>${counts.filter(n=>n>0).length}/${names.length}</b> estudiantes hablaron</span><span><b>${counts.reduce((a,b)=>a+b,0)}</b> intervenciones confirmadas</span></div>${button('Volver a preparar la misión','restart','primary')}<p class="muted">Prototipo independiente. Este resultado no modifica el progreso de los juegos publicados.</p></main>`;}
root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action!;
if(a==='start'){const entered=(root.querySelector<HTMLTextAreaElement>('#names')!.value).split(',').map(s=>s.trim()).filter(Boolean);if(entered.length&&(entered.length<8||entered.length>13||new Set(entered.map(n=>n.toLowerCase())).size!==entered.length)){root.querySelector('#error')!.textContent='Usa de 8 a 13 nombres distintos, o deja la lista vacía.';return;}names=entered.length?entered:Array.from({length:10},(_,i)=>`Estudiante ${i+1}`);counts=names.map(()=>0);queue=Array.from({length:14},(_,i)=>i%names.length);seconds=Number(root.querySelector<HTMLSelectElement>('#duration')!.value);started=true;render();return;}
if(a==='restart'){started=false;finished=false;credited=Array(14).fill(false);round=step=0;energy=4;paused=false;showAnswer=hidden=pending=false;selected=-1;words=[];feedback='';setup();return;}
if(a==='pause'){paused=!paused;render();return;}if(finished||paused)return;
if(a==='finish'){if(confirm('¿Terminar la prueba sin completar la misión?')){finished=true;render();}return;}
if(a==='success'&&!pending){pending=true;recordVoice();if(step===0){step=1;feedback='First voice received. Pass the signal!';}else{round++;step=0;energy=Math.min(4,energy+1);feedback='Signal connected! The bridge is growing.';hidden=false;selected=-1;words=[];}showAnswer=false;if(round===7)finished=true;render();setTimeout(()=>{pending=false;render();},500);return;}
if(a==='retry'){recordVoice();energy=Math.max(0,energy-1);feedback=energy?'Signal weakening. Take a breath and try again.':'Signal lost. Time for another expedition.';if(!energy)finished=true;render();return;}
if(a==='swap'){const position=round*2+step;if(credited[position]){feedback='Este estudiante ya intervino. Dale apoyo para completar su turno.';render();return;}const candidates=queue.map((id,i)=>({id,i})).filter(x=>x.i>position&&x.id!==queue[position]).sort((x,y)=>counts[x.id]!-counts[y.id]!||x.i-y.i);if(candidates[0]){const j=candidates[0].i;[queue[position],queue[j]]=[queue[j]!,queue[position]!];feedback='Turn exchanged. The original student still has a later turn.';}else{feedback='No quedan turnos para intercambiar. Da apoyo al estudiante actual.';}showAnswer=false;}
if(a==='answer')showAnswer=!showAnswer;if(a==='hide')hidden=!hidden;if(a.startsWith('option:'))selected=Number(a.split(':')[1]);if(a.startsWith('word:'))words.push(a.slice(5));if(a==='reset')words=[];render();});
setInterval(()=>{if(started&&!finished&&!paused&&!pending){seconds=Math.max(0,seconds-1);if(!seconds){finished=true;render();}else{const clock=root.querySelector('#clock');if(clock)clock.textContent=time();}}},1000);
setup();
