import {spotlightChallenges as allCards} from './data/content';
import {readClass,beginClass,recordVoice,fairQueue} from './class-session';
let cards=allCards;
const app=document.querySelector<HTMLDivElement>('#spotlight')!;
type Phase='setup'|'look'|'think'|'say'|'reward'|'end';
let phase:Phase='setup', names:string[]=[], counts:number[]=[], queue:number[]=[], recorded:boolean[]=[], round=0, speaker=0, remaining=600, duration=600, thought=4, paused=false, muted=false, calm=matchMedia('(prefers-reduced-motion: reduce)').matches, hint=false, solution=false, chosen=-1, words:string[]=[], revealed=new Set<number>(), feedback='', outcome='early', lockUntil=0, rewardUntil=0, last=performance.now();
let audio:AudioContext|undefined;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const btn=(text:string,action:string,cls='',disabled=false)=>`<button type="button" class="${cls}" data-act="${action}" ${disabled?'disabled':''}>${text}</button>`;
const time=()=>`${Math.floor(Math.ceil(remaining)/60)}:${String(Math.ceil(remaining)%60).padStart(2,'0')}`;
function sound(type:'good'|'wrong'|'win'|'tap'){if(muted)return;try{audio??=new AudioContext();void audio.resume();const notes=type==='win'?[523,659,784,1047]:type==='good'?[523,784]:type==='wrong'?[185,140]:[440];notes.forEach((f,i)=>{const o=audio!.createOscillator(),g=audio!.createGain(),t=audio!.currentTime+i*.12;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.25);o.connect(g);g.connect(audio!.destination);o.start(t);o.stop(t+.27);});}catch{/* Optional sound. */}}
function header(){return `<header class="hud"><img class="logo" src="/missions/v1/assets/english4kids-logo.png" alt="English4Kids"><div class="brand"><strong>🔦 Mystery Spotlight</strong><small>VISTA PREVIA · NIVEL 2 · SEMANA 4 · DÍA 1</small></div><div class="hud-progress"><span>◆</span><b>${round} / ${cards.length}</b><small>cristales</small></div><div class="clock ${remaining<=30?'urgent':''}" role="timer" aria-label="Tiempo restante"><small>TIEMPO RESTANTE</small><b id="time">${time()}</b></div><div class="tools">${btn(muted?'🔇':'♫','mute','icon')}${btn('⛶','fullscreen','icon')}${phase!=='setup'&&phase!=='end'?btn('Ⅱ','pause','icon'):''}</div></header>`;}
function crystals(){return `<div class="crystal-track" aria-label="${round} de ${cards.length} cristales">${cards.map((_,i)=>`<span class="gem ${i<round?'lit':''}">◆</span>`).join('')}</div>`;}
function setup(){return `<main class="setup"><section class="invitation"><p class="eyebrow">LOOK. THINK. SPEAK. UNLOCK.</p><h1>Your voices<br>unlock the <em>treasure.</em></h1><p>Descubran las figuras y recuperen los cristales de luz. Cada reto necesita dos voces.</p>${crystals()}<p class="preview-note"><a href="/missions/v1/day.html">← Las tres misiones del día</a></p></section><form class="setup-panel" id="setup"><h2>Prepara la expedición</h2><label for="names">Participantes · 8–13 nombres separados por comas</label><textarea id="names" placeholder="Ana, Luis, Juan, Sofía…">${esc(readClass().names.join(", "))}</textarea><small>Primero quienes menos hablaron. Vacío: 10 participantes de prueba.</small><label for="minutes">Tiempo que elige el coach</label><select id="minutes"><option value="10">10 minutos</option><option value="3">3 minutos · 3 cristales</option><option value="5">5 minutos</option><option value="8">8 minutos</option><option value="12">12 minutos</option><option value="15">15 minutos</option></select><label class="check"><input id="calm" type="checkbox" ${calm?'checked':''}> Reducir movimiento</label><div class="rules">Correcto: avanza la voz. Dos voces completan un cristal.<br>Con ayuda: −5 s · Incorrecto: −10 s y reintenta.<br>La selección en pantalla no sustituye la respuesta oral.</div><p id="error" role="alert"></p>${btn('Entrar a la cueva →','start','primary')}</form></main>`;}
function pictures(){const c=cards[round]!,paths:Record<string,string>={triangle:'<path d="M50 7 94 91 6 91Z"/>',circle:'<circle cx="50" cy="50" r="40"/>',star:'<path d="M50 4 63 34 97 36 71 60 79 94 50 76 21 94 29 60 3 36 37 34Z"/>',heart:'<path d="M50 91C-25 43 8-16 50 21 92-16 125 43 50 91Z"/>',square:'<rect x="10" y="10" width="80" height="80" rx="6"/>',oval:'<ellipse cx="50" cy="50" rx="46" ry="28"/>',rectangle:'<rect x="4" y="24" width="92" height="52" rx="5"/>'};const memory=c.kind==='REMEMBER'&&phase==='say';return `<div class="picture-stage ${phase==='look'?'exploring':''}"><div class="shapes" aria-label="${phase==='look'?'Imagen misteriosa':memory?'Imagen oculta':`${c.count} ${c.shape}`}">${memory?'<span class="memory">✦ ? ✦</span>':Array.from({length:c.count},()=>`<svg aria-hidden="true" viewBox="0 0 100 100" style="color:${c.color}">${paths[c.shape]}</svg>`).join('')}</div>${phase==='look'?`<div class="shutters">${Array.from({length:6},(_,i)=>`<button data-act="reveal:${i}" aria-label="Revelar pista ${i+1}" class="${revealed.has(i)?'revealed':''}" ${revealed.has(i)?'disabled':''}>${revealed.has(i)?'':`✦ ${i+1}`}</button>`).join('')}</div>`:''}</div>`;}
function roster(){return `<details class="roster"><summary>Coach · ${counts.filter(c=>c>0).length}/${names.length} participaron</summary><div>${names.map((n,i)=>`<span>${esc(n)} <b>${counts[i]}</b></span>`).join('')}</div></details>`;}
function game(){const c=cards[round]!,id=queue[round*2+speaker]!,other=queue[round*2+1]!;return `<div class="turn"><span>🎤 <b>${esc(names[id]!)}</b> ${speaker?'completa':'responde'}</span>${!speaker?`<span class="next">💬 Después: ${esc(names[other]!)}</span>`:'<span class="next">Segunda voz · completa el cristal</span>'}</div><main class="play"><section class="board"><nav class="steps" aria-label="Etapas del reto">${['look','think','say'].map(p=>`<span class="${phase===p?'active':''}">${p==='look'?'◉ LOOK':p==='think'?'✦ THINK':'▰ SAY'}</span>`).join('<i>→</i>')}</nav><div class="challenge-meta">CRISTAL ${round+1} / ${cards.length} · ${phase==='say'?c.kind:'MYSTERY SPOTLIGHT'}</div>${pictures()}${phase==='look'?`<h1>What can you discover?</h1><p>El coach revela pistas. Todos observan.</p>${btn('Ya lo vimos → THINK','think','phase-next',revealed.size===0)}`:phase==='think'?`<h1>Everyone, think!</h1><p>Remember the shapes, colors and number.</p><div class="think-count" id="think-count">${Math.ceil(thought)}</div>`:`<h1 class="prompt">${esc(c.prompt)}</h1>${c.options?`<div class="options ${c.options.length===2?'two':''}">${c.options.map((o,i)=>`<button data-act="option:${i}" aria-pressed="${chosen===i}" class="${chosen===i?'selected':''}">${esc(o)}</button>`).join('')}</div>`:''}${c.words?`<div class="assembled">${esc(words.join(' '))||'Construye el mensaje…'}</div><div class="words">${c.words.filter(w=>!words.includes(w)).map(w=>btn(esc(w),'word:'+w)).join('')}${btn('↺','reset')}</div>`:''}<p class="speaking-task"><b>${esc(names[id]!)}:</b> ${esc(speaker?c.follow:c.lead)}</p>${hint?`<div class="hint">💡 Una figura: “There is…” · Más de una: “There are…”</div>`:''}${solution?`<div class="hint">Referencia: ${esc(c.answers[speaker]!)}</div>`:''}`}</section></main>${crystals()}${roster()}<footer class="dock"><small>COACH</small><div>${btn('✓ Correcto','correct','correct',phase!=='say')}${btn('🤝 Con ayuda','help','help',phase!=='say')}${btn('↻ Incorrecto','wrong','wrong',phase!=='say')}${btn('💡 Pista','hint','',phase!=='say')}${btn('•••','menu','icon')}</div></footer>`;}
function ending(){const win=outcome==='win';return `<main class="ending ${win?'win':''}"><p class="eyebrow">${win?'MISSION COMPLETE':outcome==='timeout'?'TIME’S UP':'MISIÓN TERMINADA'}</p><div class="vault-finale" aria-hidden="true"><div class="vault-light"></div><div class="door left-door"></div><div class="door right-door"></div><span class="treasure">💎</span></div><h1>${win?'You unlocked the treasure!':'The treasure awaits.'}</h1><p>${win?'Dos voces por reto. Una gran misión juntos.':'Hoy recuperaron '+round+' cristales. Pueden volver a intentarlo.'}</p><div class="end-stats"><span><b>${round}/${cards.length}</b>cristales</span><span><b>${counts.filter(c=>c>0).length}/${names.length}</b>participaron</span><span><b>${counts.reduce((a,b)=>a+b,0)}</b>turnos con voz</span></div>${btn('Jugar otra vez','restart','primary')} <a class="day-link" href="/missions/v1/day.html">Elegir la siguiente misión →</a>${win?'<div class="sparkles" aria-hidden="true">'+Array.from({length:22},(_,i)=>`<i style="--x:${i*4.6}%;--d:${i%5*.2}s">✦</i>`).join('')+'</div>':''}</main>`;}
function render(){document.body.dataset.calm=String(calm);app.innerHTML=header()+(phase==='setup'?setup():phase==='end'?ending():phase==='reward'?`<main class="reward"><div class="flying-gem">◆</div><h1>Crystal unlocked!</h1><p>¡Dos voces conectaron la luz!</p>${crystals()}</main>`:game())+`<div class="feedback ${feedback.includes('−')?'penalty':''}" role="status">${esc(feedback)}</div>`+(paused?`<div class="overlay"><section><h2>Misión en pausa</h2><p>El reloj está detenido.</p>${btn('Continuar','pause','primary')}${btn('Ver respuesta de referencia','solution','',phase!=='say')}${btn('Intercambiar participante','swap','',phase!=='say')}${btn('Terminar prueba','finish')}</section></div>`:'');app.querySelectorAll<HTMLButtonElement>('[data-act="mute"]').forEach(b=>b.setAttribute('aria-label',muted?'Activar sonido':'Silenciar'));app.querySelectorAll<HTMLButtonElement>('[data-act="fullscreen"]').forEach(b=>b.setAttribute('aria-label','Pantalla completa'));app.querySelectorAll<HTMLButtonElement>('[data-act="pause"]').forEach(b=>b.setAttribute('aria-label',paused?'Continuar':'Pausa'));}
function finish(reason:string){outcome=reason;phase='end';paused=false;feedback='';if(reason==='win')sound('win');else sound('wrong');render();}
function record(){const pos=round*2+speaker;if(!recorded[pos]){counts[queue[pos]!]!++;recordVoice(names[queue[pos]!]!);recorded[pos]=true;}}
function newRound(){speaker=0;revealed=new Set();hint=solution=false;chosen=-1;words=[];feedback='';phase='look';render();}
function act(action:string){if(action==='mute'){muted=!muted;const b=app.querySelector<HTMLButtonElement>('[data-act="mute"]');if(b){b.textContent=muted?'🔇':'♫';b.setAttribute('aria-label',muted?'Activar sonido':'Silenciar');}return;}if(action==='fullscreen'){if(!document.fullscreenElement)void document.documentElement.requestFullscreen().catch(()=>{});else void document.exitFullscreen();return;}if(action==='start'&&phase==='setup'){const list=app.querySelector<HTMLTextAreaElement>('#names')!.value.split(',').map(s=>s.trim()).filter(Boolean);if(list.length&&(list.length<8||list.length>13||new Set(list.map(s=>s.toLowerCase())).size!==list.length)){app.querySelector('#error')!.textContent='Escribe entre 8 y 13 nombres distintos, o deja vacío para probar.';return;}names=list.length?list:Array.from({length:10},(_,i)=>`Explorador ${i+1}`);duration=Number(app.querySelector<HTMLSelectElement>('#minutes')!.value)*60;remaining=duration;calm=app.querySelector<HTMLInputElement>('#calm')!.checked;counts=names.map(()=>0);beginClass(names,duration/60);cards=allCards.slice(0,duration<=180?3:duration<=300?5:7);queue=fairQueue(names,cards.length*2);recorded=Array(cards.length*2).fill(false);round=0;speaker=0;paused=false;lockUntil=0;last=performance.now();sound('tap');newRound();return;}
if(action==='restart'&&phase==='end'){phase='setup';round=0;remaining=duration;feedback='';render();return;}
if(phase==='end'||phase==='setup')return;
if(action==='pause'||action==='menu'){paused=!paused;last=performance.now();render();return;}
if(paused){if(action==='solution'){if(phase==='say'){solution=!solution;paused=false;render();}return;}if(action==='finish'){finish('early');return;}if(action==='swap'&&phase==='say'){const pos=round*2+speaker;if(recorded[pos]){feedback='Ya intervino. Dale apoyo para completar su turno.';}else{const candidates=queue.map((id,i)=>({id,i})).filter(x=>x.i>pos&&x.id!==queue[pos]).sort((a,b)=>counts[a.id]!-counts[b.id]!||a.i-b.i);if(candidates[0]){const j=candidates[0].i;[queue[pos],queue[j]]=[queue[j]!,queue[pos]!];feedback='Turno intercambiado. Recuperará su intervención después.';}else feedback='No quedan turnos para intercambiar.';}paused=false;render();}return;}
if(action.startsWith('reveal:')&&phase==='look'){revealed.add(Number(action.split(':')[1]));sound('tap');render();return;}
if(action==='think'&&phase==='look'&&revealed.size){phase='think';thought=4;render();return;}
if(phase!=='say')return;
if(action.startsWith('option:')){chosen=Number(action.split(':')[1]);sound('tap');render();return;}
if(action.startsWith('word:')){const w=action.slice(5);if(!words.includes(w))words.push(w);sound('tap');render();return;}
if(action==='reset'){words=[];render();return;}if(action==='hint'){hint=!hint;render();return;}
if(!['correct','help','wrong'].includes(action)||performance.now()<lockUntil)return;lockUntil=performance.now()+650;record();
if(action==='wrong'){remaining=Math.max(0,remaining-10);feedback='−10 s · Respira y vuelve a intentarlo.';sound('wrong');if(!remaining)finish('timeout');else render();return;}
if(action==='help'){remaining=Math.max(0,remaining-5);if(!remaining){finish('timeout');return;}}
sound('good');feedback=action==='help'?'−5 s · ¡Lo lograron con apoyo!':'¡Voz recibida!';hint=solution=false;
if(speaker===0){speaker=1;render();}else{round++;if(round===cards.length){finish('win');return;}phase='reward';rewardUntil=performance.now()+1500;render();}}
app.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-act]');if(b&&!b.disabled)act(b.dataset.act!);});
app.addEventListener('submit',e=>{e.preventDefault();if(phase==='setup')act('start');});
document.addEventListener('keydown',e=>{if(e.repeat||(e.target as HTMLElement).matches('input,textarea,select'))return;const a:Record<string,string>={c:'correct',h:'help',r:'wrong',p:'pause'};if(a[e.key.toLowerCase()]){e.preventDefault();act(a[e.key.toLowerCase()]!);}});
setInterval(()=>{const now=performance.now(),delta=(now-last)/1000;last=now;if(paused){if(phase==='reward')rewardUntil+=delta*1000;return;}if(phase==='setup'||phase==='end')return;if(phase==='reward'){if(now>=rewardUntil)newRound();return;}remaining=Math.max(0,remaining-delta);if(!remaining){finish('timeout');return;}const clock=app.querySelector('#time');if(clock)clock.textContent=time();app.querySelector('.clock')?.classList.toggle('urgent',remaining<=30);if(phase==='think'){thought-=delta;if(thought<=0){phase='say';render();}else{const t=app.querySelector('#think-count');if(t)t.textContent=String(Math.ceil(thought));}}},100);
render();
