import {moduleTargets} from './rotation-scenes';
export const EXPLORER_FINALE_MS=3600;
const labels=['Scanner','Grippers','Legs'];
export function explorerModule(parts:number[],target:number){const caps=moduleTargets(target);return [0,2,1].find(i=>parts[i]<caps[i])??-1;}
export function explorerScene(parts:number[],target:number,state:string,selected:number,finale=false,elapsed=0,calm=false){
 const caps=moduleTargets(target),done=parts.map((n,i)=>n>=caps[i]),win=state==='win',total=parts.reduce((a,b)=>a+b,0);
 const part=(i:number,art:string)=>`<g class="explorer-piece ${done[i]?'complete':''} ${state==='success'&&selected===i?'installing':''}" style="--piece-x:${i===0?'-65px':i===1?'75px':'-50px'};--piece-y:${i===0?'-35px':'35px'};opacity:${parts[i]===0?.22:1}">${art}</g>`;
 const robot=`<svg viewBox="0 0 240 300" aria-label="Robot: ${total} of ${target} components installed" role="img"><ellipse cx="120" cy="277" rx="86" ry="12" fill="#081e2c"/>${part(2,'<g stroke="#b2e6df" stroke-width="17" stroke-linecap="round"><path d="M94 212v48H76M146 212v48h18"/></g>')}<rect x="74" y="118" width="92" height="96" rx="22" fill="#467b91" stroke="#bdede3" stroke-width="5"/><path d="m120 143 22 23-22 23-22-23Z" fill="#ffe294"/>${part(1,'<g fill="none" stroke="#9adcd7" stroke-width="15" stroke-linecap="round"><path d="m72 143-23 27-17-14M168 143l23 27 17-14"/></g>')}${part(0,'<path d="M120 54V31" stroke="#aedbdc" stroke-width="5"/><circle cx="120" cy="27" r="8" fill="#ffe294"/><rect x="66" y="57" width="108" height="57" rx="19" fill="#a5dcd5" stroke="#e0fff3" stroke-width="4"/><rect x="77" y="68" width="86" height="33" rx="10" fill="#123342"/><path d="M91 80v8m58-8v8m-42 1q13 12 26 0" fill="none" stroke="#acffcf" stroke-width="5" stroke-linecap="round"/>')}</svg>`;
 const message=finale?'Locate → Walk → Collect → Power on':win?'Battery delivered. You powered the station!':state==='mistake'?'Connection failed. Try the same message again.':state==='success'&&selected>=0?(done[selected]?`${labels[selected]} online! New ability unlocked.`:'Component installed! One step closer.'):done[0]?(done[2]?'Movement ready. Build the grippers to collect the battery.':'Battery located! Build the legs to reach it.'):'Build the scanner to locate the missing battery.';
 return `<section class="explorer-workshop ${finale?'delivery':''} ${win?'powered':''} ${calm?'reduced':''}" style="--elapsed:-${elapsed}ms"><div class="explorer-heading"><span>OPERATION: POWER THE STATION</span><strong>${win?'MISSION ACCOMPLISHED':`${total} / ${target} components installed`}</strong></div><div class="explorer-stage"><div class="explorer-station"><span>BASE</span><i></i><i></i><i></i></div><div class="explorer-track"></div><div class="explorer-robot ${done[2]?'can-walk':''} ${state==='success'&&selected===2&&done[2]?'test-walk':''}">${robot}<div class="explorer-carried">ϟ</div></div><div class="explorer-beam ${done[0]?'scanned':''}"></div><div class="explorer-battery ${done[0]?'located':''}"><span>ϟ</span><small>${done[0]?'BATTERY FOUND':'UNKNOWN SIGNAL'}</small></div><div class="explorer-power">STATION ONLINE</div></div><div class="explorer-modules">${[0,2,1].map(i=>`<div class="${done[i]?'done':selected===i?'active':''}"><b>${done[i]?'✓ ':''}${labels[i]}</b><span>${['Locate the battery','Collect & deliver','Walk across the workshop'][i]}</span><div class="explorer-slots">${Array.from({length:caps[i]},(_,n)=>`<i class="${n<parts[i]?'filled':''} ${state==='success'&&selected===i&&n===parts[i]-1?'new':''}"></i>`).join('')}</div></div>`).join('')}</div><p class="explorer-message" role="status">${message}</p></section>`;
}
