import {readClass,beginClass,recordVoice,parseNames,validNames,escapeHtml as esc} from '../class-session';
import {gameHud,gamePressure,gameButton as btn} from './visual-standard';
import {createGameAudio} from './game-audio';
import './mystery-smoothie.css';
const fruits=['strawberries','grapes','mangoes'] as const;
const colors=['#f46483','#ab7ee6','#ffc755'];
function fruit(index:number,shadow=false){const fill=shadow?'#273e55':colors[index];return `<svg viewBox="0 0 100 100" role="img" aria-label="${shadow?'Mystery fruit silhouette':fruits[index]}">${index===0?`<path d="M20 39Q17 21 50 28Q83 21 80 39Q72 75 50 90Q28 75 20 39Z" fill="${fill}"/><path d="M50 30 28 17 44 19 50 6 57 19 74 16Z" fill="${shadow?fill:'#80bd77'}"/>${shadow?'':'<path d="m35 40 2 5m22-5 2 5m-17 9 2 5m17-5 2 5m-14 12 2 5" stroke="#ffe499" stroke-width="3"/>'}`:index===1?`${[[32,32],[56,30],[74,44],[27,53],[49,51],[62,65],[39,73],[52,87]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="12" fill="${fill}" stroke="${shadow?fill:'#8662bd'}" stroke-width="2"/>`).join('')}<path d="M49 27Q63 5 75 9Q68 29 49 27" fill="${shadow?fill:'#7bb87a'}"/>`:`<path d="M65 15C98 35 77 86 40 91C9 94 6 69 25 45C39 27 32 10 65 15Z" fill="${fill}"/><path d="M56 17Q67 2 84 8Q80 23 56 17" fill="${shadow?fill:'#7bb87a'}"/>`}</svg>`;}
export function runMysterySmoothie(root:HTMLElement){
 const audio=createGameAudio(),saved=readClass();let names=saved.names.length?saved.names:Array.from({length:10},(_,i)=>`Player ${i+1}`),minutes=[3,5,8,10,15].includes(saved.minutes)?saved.minutes:5;
 let screen:'setup'|'play'|'end'='setup',phase:'guess'|'drop'|'blend'='guess',queue:number[]=[],steps:{fruit:number;count:number}[]=[],sizes:number[]=[],turn=0,recipe=0,filled=0,remaining=300,lives=4,paused=false,muted=false,hint=false,help=false,message='',error='',delay=0,last=performance.now(),selected=-1,early=false;
 let added:{fruit:number;count:number}[]=[],spoken=new Set<string>(),recorded=new Set<number>();
 const current=()=>steps[turn];
 function mark(){if(!recorded.has(turn)){recordVoice(names[queue[turn]]);spoken.add(names[queue[turn]]);recorded.add(turn);}}
 function finish(endEarly=false){early=endEarly;screen='end';paused=false;audio.stop();void audio.play(!early&&filled===3?'victory':'incorrect');render();}
 function start(){names=parseNames((root.querySelector('#names') as HTMLTextAreaElement).value);if(!validNames(names)){error='Enter 8–13 different names.';render();return;}minutes=Number((root.querySelector('#duration') as HTMLSelectElement).value);beginClass(names,minutes);const session=readClass();queue=names.map((_,i)=>i).sort((a,b)=>session.spoken[a]-session.spoken[b]);sizes=[0,1,2].map(i=>Math.floor(names.length/3)+(i<names.length%3?1:0));steps=queue.map((_,i)=>({fruit:(i+Math.floor(i/3))%3,count:1+Math.floor(Math.random()*3)}));for(let i=steps.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[steps[i],steps[j]]=[steps[j],steps[i]];}screen='play';phase='guess';turn=recipe=filled=0;remaining=minutes*60;lives=4;added=[];spoken=new Set();recorded=new Set();hint=help=paused=false;message='';selected=-1;last=performance.now();void audio.unlock();render();}
 function choose(index:number){if(phase!=='guess')return;selected=index;mark();if(index!==current().fruit){lives--;message='Not this ingredient. Try the clue again!';void audio.play('incorrect');if(!lives)finish();else render();return;}if(help)remaining=Math.max(0,remaining-5);if(!remaining){finish();return;}added.push({fruit:index,count:current().count});phase='drop';delay=900;message='Ingredient discovered!';void audio.play('correct');render();}
 function advance(){if(phase==='drop'&&added.length===sizes[recipe]){phase='blend';delay=1500;message='Recipe complete. Mixing!';render();return;}if(phase==='blend'){filled++;if(filled===3){finish();return;}recipe++;added=[];}turn++;phase='guess';hint=help=false;selected=-1;message='';render();}
 function blender(){return `<div class="mystery-blender ${phase}"><div class="blender-lid"></div><div class="blender-jar"><div class="blend-liquid" style="height:${phase==='blend'?85:added.length/sizes[recipe]*70}%;background:${colors[recipe]}"></div><div class="jar-ingredients">${added.map(i=>`<span class="ingredient-batch">${fruit(i.fruit)}<b>×${i.count}</b></span>`).join('')}</div><div class="jar-lines">—<br>—<br>—</div></div><div class="blender-base"><i></i><b>E4K</b></div><span>${phase==='blend'?'MIXING!':`${added.length}/${sizes[recipe]} ingredients discovered`}</span></div>`;}
 function render(){
 const setup=`<section class="smoothie-setup"><h1>Mystery Smoothie</h1><h2>Discover three secret recipes!</h2><p>Use the shape, color and quantity clues. Say a full sentence naming the fruit and its quantity. Your coach listens, then selects the fruit you named.</p><p>Each correct ingredient drops into the blender. Discover the whole recipe to mix and fill a glass. Fill all three glasses before closing time!</p><p>Everyone gets an ingredient to discover. A wrong fruit or spoken answer uses one life; try again. The sentence starter costs 5 seconds only when the answer is accepted.</p><label>Time limit<select id="duration">${[3,5,8,10,15].map(n=>`<option ${minutes===n?'selected':''}>${n}</option>`).join('')}</select></label><label>8–13 students, separated by commas<textarea id="names">${esc(names.join(', '))}</textarea></label><p role="alert">${error}</p>${btn('Open the lab','start','success')}</section>`;
 const ending=`<section class="smoothie-setup"><h1>${early?'Lab closed early':filled===3?'Three mystery smoothies ready!':'The recipes are not finished yet'}</h1><div class="smoothie-glasses">${[0,1,2].map(i=>`<div class="smoothie-glass ${i<filled?'full':''}" style="--drink:${colors[i]}"><span>${i<filled?'✓':'?'}</span></div>`).join('')}</div><p>${filled}/3 smoothies · ${spoken.size}/${names.length} students heard</p>${btn('Play again','again','success')}<a class="game-button" href="/missions/v1/day.html?day=4">Day 4 missions</a></section>`;
 const play=screen==='play'?`<div class="game-speaker"><strong>${esc(names[queue[turn]])}</strong><span>INGREDIENT DETECTIVE</span><small>Next: ${turn+1<queue.length?esc(names[queue[turn+1]]):'Final ingredient'} · ${spoken.size}/${names.length} have spoken</small></div><main class="smoothie-main">${gamePressure({seconds:remaining,lives,paused})}<div class="smoothie-goal"><b>DISCOVER 3 RECIPES</b><div class="smoothie-glasses">${[0,1,2].map(i=>`<div class="smoothie-glass ${i<filled?'full':''} ${i===recipe?'active':''}" style="--drink:${colors[i]}"><span>${i<filled?'✓':i+1}</span></div>`).join('')}</div><span>Recipe ${recipe+1}/3</span></div><div class="smoothie-workbench">${blender()}<section class="ingredient-task"><span class="eyebrow">SECRET INGREDIENT</span><h1>Which fruit? How many?</h1><div class="ingredient-clues"><div><span>SHAPE</span>${fruit(current().fruit,true)}</div><div><span>COLOR</span><i class="color-clue" style="background:${colors[current().fruit]}"></i></div><div><span>QUANTITY</span><b class="quantity-clue">${Array.from({length:current().count},()=>'<i></i>').join('')}</b></div></div><div class="ingredient-options">${fruits.map((f,i)=>`<button data-fruit="${i}" ${phase!=='guess'?'disabled':''} class="${selected===i?(i===current().fruit?'correct':'wrong'):''}">${fruit(i)}<b>${f}</b></button>`).join('')}</div><p>Say a full sentence. Your coach selects the fruit you name.</p>${hint?'<p class="smoothie-hint">There is one ____. / There are ____ ____.</p>':''}<div role="status">${esc(message)}</div></section></div></main><footer class="game-coach"><span>Listen for the fruit, quantity and full sentence before selecting.</span>${btn('Sentence starter −5 s','hint','warning',phase!=='guess')}${btn('Spoken answer: retry','retry','danger',phase!=='guess')}${btn(muted?'Sound off':'Sound on','sound')}</footer>`:'';
 root.innerHTML=`<div class="game-shell mystery-smoothie" data-paused="${paused}">${gameHud({title:'Mystery Smoothie',seconds:remaining,lives,paused})}<nav class="mission-nav"><a href="/missions/v1/day.html?day=4">Day 4 missions</a><span>Food · Shapes · Colors · Quantities</span>${screen==='play'?btn('End mission','end'):''}</nav>${screen==='setup'?setup:screen==='end'?ending:play}${paused?`<div class="week-pause"><section><h1>Lab paused</h1>${btn('Resume','pause','success')}${btn('End now','finish','danger')}</section></div>`:''}</div>`;
 }
 root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='fullscreen'){if(document.fullscreenElement)void document.exitFullscreen();else void root.requestFullscreen();return;}if(a==='start'){start();return;}if(a==='again'){screen='setup';render();return;}if(a==='sound'){muted=!muted;audio.setMuted(muted);render();return;}if(a==='pause'&&screen==='play'){paused=!paused;last=performance.now();if(paused)audio.stop();render();return;}if(a==='finish'&&paused){finish(true);return;}if(screen!=='play'||paused||phase!=='guess')return;if(a==='end'){paused=true;render();return;}if(a==='hint'){help=true;hint=!hint;render();return;}if(a==='retry'){mark();lives--;message='Try the full sentence again. Check the quantity!';void audio.play('incorrect');if(!lives)finish();else render();return;}if(b.dataset.fruit!==undefined)choose(Number(b.dataset.fruit));});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='play'){paused=true;audio.stop();render();}});
 setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;if(paused||screen!=='play')return;if(phase!=='guess'){delay-=dt*1000;if(delay<=0)advance();return;}remaining=Math.max(0,remaining-dt);if(!remaining){finish();return;}const n=Math.ceil(remaining),c=root.querySelector('.game-clock');if(c){c.classList.toggle('danger',n<=30);c.classList.toggle('warning',n>30&&n<=60);c.querySelector('b')!.textContent=`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}},100);
 render();
}
