import {readClass,beginClass,recordVoice,parseNames,validNames,escapeHtml as esc} from '../class-session';
import {gameHud,gamePressure,gameButton as btn} from './visual-standard';
import {createGameAudio} from './game-audio';
import {trainingRobot,foodIcon} from './training-robot';
import './robot-orders.css';

// A spoken order and a spoken check are separate roles; selecting food never grades speech.
export function runRobotOrders(root:HTMLElement){
 const audio=createGameAudio(),saved=readClass(),foods=['strawberries','mangoes','grapes','carrots','onions','potatoes'];
 let names=saved.names.length?saved.names:Array.from({length:10},(_,i)=>`Player ${i+1}`),minutes=[3,5,8,10,15].includes(saved.minutes)?saved.minutes:5;
 let screen:'setup'|'play'|'end'='setup',phase:'order'|'check'|'delivery'='order',queue:number[]=[],round=0,total=5,served=0,lives=4,remaining=300,paused=false,muted=false,like='',dislike='',tray='',hint=false,message='',error='',delay=0,last=performance.now(),endedEarly=false;
 let spoken=new Set<string>(),recorded=new Set<number>(),mistakes:boolean[]=[];
 const activeIndex=()=>round*2+(phase==='order'?0:1);
 const active=()=>names[queue[activeIndex()]];
 function mark(){const i=activeIndex();if(!recorded.has(i)){recordVoice(active());spoken.add(active());recorded.add(i);}}
 function nextOrder(){round++;phase='order';like='';dislike='';tray='';hint=false;message='';if(round===total)finish();else render();}
 function finish(early=false){endedEarly=early;screen='end';paused=false;delay=0;audio.stop();void audio.play(!early&&served===total?'victory':'incorrect');render();}
 function start(){names=parseNames((root.querySelector('#names') as HTMLTextAreaElement).value);if(!validNames(names)){error='Enter 8–13 different names.';render();return;}minutes=Number((root.querySelector('#duration') as HTMLSelectElement).value);beginClass(names,minutes);const s=readClass();queue=names.map((_,i)=>i).sort((a,b)=>s.spoken[a]-s.spoken[b]);if(queue.length%2)queue.push(queue[0]);total=queue.length/2;mistakes=Array.from({length:total},(_,i)=>i%2===0);for(let i=mistakes.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[mistakes[i],mistakes[j]]=[mistakes[j],mistakes[i]];}screen='play';phase='order';round=served=0;lives=4;remaining=minutes*60;spoken=new Set();recorded=new Set();like=dislike=tray=message='';paused=false;hint=false;last=performance.now();void audio.unlock();render();}
 function grade(result:string){if(phase==='delivery'||phase==='order'&&(!like||!dislike))return;mark();if(result==='wrong'){lives--;message='Try again. Look at the food clues.';void audio.play('incorrect');if(!lives)finish();else render();return;}if(result==='help')remaining=Math.max(0,remaining-5);if(!remaining){finish();return;}void audio.play('correct');hint=false;if(phase==='order'){tray=mistakes[round]?dislike:like;phase='check';message='The robot has prepared the tray. Check the order!';}else{tray=like;phase='delivery';served++;message='Order checked. Delivery on its way!';delay=1800;}render();}
 function robot(){return trainingRobot({stage:'deliver',wanted:like||foods[0],wrong:dislike||foods[4],request:''},phase==='delivery'?'success':'idle',7,7).match(/<svg[\s\S]*?<\/svg>/)?.[0]||'';}
 function render(){
 const setup=`<section class="orders-setup"><h1>Robot Café</h1><h2>Serve every customer before closing time.</h2><p>1. Customer: choose one food you like and one you don’t like. Say both sentences. Your coach marks the food clues.</p><p>2. Order checker: use the same customer’s preferences. Check the robot’s tray and say what is right or wrong.</p><p>Each checked order leaves the queue. Four lives; an incorrect spoken answer uses one life and gets another try. Help costs 5 seconds.</p><p>Everyone speaks. With an odd class size, one student has a second role.</p><label>Time limit<select id="duration">${[3,5,8,10,15].map(n=>`<option ${n===minutes?'selected':''}>${n}</option>`).join('')}</select></label><label>8–13 students, separated by commas<textarea id="names">${esc(names.join(', '))}</textarea></label><p role="alert">${error}</p>${btn('Open the café','start','success')}</section>`;
 const end=`<section class="orders-setup"><h1>${endedEarly?'Café closed early':served===total?'Every customer served!':'Some customers are still waiting'}</h1><p>${served} / ${total} orders delivered · ${spoken.size} / ${names.length} students heard</p>${btn('Play again','again','success')}<a class="game-button" href="/missions/v1/day.html?day=2">Day 2 missions</a></section>`;
 const play=screen==='play'?`<div class="game-speaker"><strong>${esc(active())}</strong><span>${phase==='order'?'CUSTOMER':phase==='check'?'ORDER CHECKER · speak as the customer':'DELIVERING'}</span><small>${spoken.size}/${names.length} have spoken · ${phase==='order'?`Next: ${esc(names[queue[round*2+1]])}`:round+1<total?`Next customer: ${esc(names[queue[(round+1)*2]])}`:'Last customer'}</small></div><main class="orders-main">${gamePressure({seconds:remaining,lives,paused})}<div class="café-queue"><b>SERVE THE QUEUE · ${served}/${total}</b>${Array.from({length:total},(_,i)=>`<span class="${i<served?'served':i===round?'current':''}">${i<served?'✓':'☺'}<small>${i+1}</small></span>`).join('')}</div><div class="orders-scene ${phase}"><aside class="preference-card"><b>CUSTOMER’S FOOD CLUES</b><div>♡ ${like?foodIcon(like):'?'} <span>${esc(like)}</span></div><div>⊗ ${dislike?foodIcon(dislike):'?'} <span>${esc(dislike)}</span></div></aside><div class="café-robot">${robot()}${phase!=='order'?`<div class="food-tray" aria-label="Tray: ${tray}">${foodIcon(tray)}<small>${esc(tray)}</small></div>`:''}</div><div class="café-customer">☺<b>${phase==='delivery'?'Thank you!':'MY ORDER'}</b></div></div><section class="orders-task"><h1>${phase==='order'?'What do you like? What don’t you like?':phase==='check'?'Check the tray. Speak as the customer.':'Delivered!'}</h1>${phase==='order'?`<p>Say both sentences. Coach: mark the foods the student names.</p><div class="food-picks">${['like','dislike'].map(role=>`<div><b>${role==='like'?'♡ LIKE':'⊗ DON’T LIKE'}</b>${foods.map(f=>`<button data-food="${f}" data-role="${role}" aria-pressed="${(role==='like'?like:dislike)===f}" ${(role==='like'?dislike:like)===f?'disabled':''}>${foodIcon(f)}<small>${f}</small></button>`).join('')}</div>`).join('')}</div>`:phase==='check'?'<p>Is it your food? Confirm it or correct the robot using your food clues.</p>':'<p>The robot has served the correct food. Next customer!</p>'}${hint?'<p class="orders-hint">I like ____. I don’t like ____.</p>':''}<div role="status">${esc(message)}</div></section></main><footer class="game-coach"><span>Coach: listen to the spoken sentences.</span>${phase!=='delivery'?btn('✓ Spoken answer accepted','correct','success',phase==='order'&&(!like||!dislike))+btn('With help −5 s','help','warning',phase==='order'&&(!like||!dislike))+btn('Try again −1 life','wrong','danger',phase==='order'&&(!like||!dislike))+btn('Sentence starter','hint'):''}${btn(muted?'Sound off':'Sound on','sound')}</footer>`:'';
 root.innerHTML=`<div class="game-shell robot-orders" data-paused="${paused}">${gameHud({title:'Robot Café',seconds:remaining,lives,paused})}<nav class="mission-nav"><a href="/missions/v1/day.html?day=2">Day 2 missions</a><span>Likes / dislikes · Check and deliver</span>${screen==='play'?btn('End mission','end'):''}</nav>${screen==='setup'?setup:screen==='end'?end:play}${paused?`<div class="week-pause"><section><h1>Café paused</h1>${btn('Resume','pause','success')}${btn('End now','finish','danger')}</section></div>`:''}</div>`;
 }
 root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='fullscreen'){if(document.fullscreenElement)void document.exitFullscreen();else void root.requestFullscreen();return;}if(a==='start'){start();return;}if(a==='again'){screen='setup';render();return;}if(a==='sound'){muted=!muted;audio.setMuted(muted);render();return;}if(a==='pause'&&screen==='play'){paused=!paused;last=performance.now();if(paused)audio.stop();render();return;}if(a==='finish'&&paused){finish(true);return;}if(screen!=='play'||paused)return;if(a==='end'){paused=true;render();return;}if(phase==='delivery')return;if(b.dataset.food&&phase==='order'){const f=b.dataset.food;if(b.dataset.role==='like'&&f!==dislike)like=f;else if(b.dataset.role==='dislike'&&f!==like)dislike=f;message='';render();return;}if(a==='hint'){hint=!hint;render();return;}if(a==='correct'||a==='help'||a==='wrong')grade(a);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='play'){paused=true;audio.stop();render();}});
 setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;if(screen!=='play'||paused)return;if(phase==='delivery'){delay-=dt*1000;if(delay<=0)nextOrder();return;}remaining=Math.max(0,remaining-dt);if(!remaining){finish();return;}const n=Math.ceil(remaining),c=root.querySelector('.game-clock');if(c){c.classList.toggle('danger',n<=30);c.classList.toggle('warning',n>30&&n<=60);c.querySelector('b')!.textContent=`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}},100);
 render();
}
