import type {RobotCue} from '../data/week';
export function foodIcon(name:string){return ({strawberries:'🍓',onions:'🧅',mangoes:'🥭',potatoes:'🥔',grapes:'🍇',carrots:'🥕'} as Record<string,string>)[name.toLowerCase()]||'';}
export function trainingRobot(cue:RobotCue,state:string,progress:number,target:number,setup=false,hideMessage=false){
 const good=state==='success'||state==='win',win=state==='win';
 const levels=[Math.ceil(target/3),Math.ceil(target*2/3),target];
 const systems=levels.map(n=>progress>=n);
 const objective=progress>=target?'Systems ready. Finish the team’s checks!':`Next: ${['activate the eyes','power the arms','unlock delivery'][systems.filter(Boolean).length]}`;
 const status=win?'HELPER CERTIFIED!':state==='mistake'?'SIGNAL LOST · TRY THE NEXT TEST':good?'MESSAGE UNDERSTOOD!':cue.stage==='recognize'?'I NEED HELP CHOOSING':cue.stage==='repair'?'MY MESSAGE NEEDS REPAIR':'TELL ME WHAT TO DELIVER';
 return `<section class="training-lab ${state} stage-${cue.stage}" data-systems="${systems.filter(Boolean).length}" aria-label="Robot training workshop"><div class="client-panel"><span>CUSTOMER MESSAGE</span><p>${hideMessage?'Build the message using these clues.':cue.request}</p><div class="client-food"><span>${foodIcon(cue.wanted)} <b>✓</b></span><span>${foodIcon(cue.wrong)} <b>×</b></span></div></div><div class="robot-bay"><div class="robot-signal">${status}</div><svg viewBox="0 0 320 260" role="img" aria-label="${good?'Robot understands the message':'Robot waiting for help'}"><defs><linearGradient id="training-metal" x2=".8" y2="1"><stop stop-color="#ddf7f0"/><stop offset="1" stop-color="#618ca8"/></linearGradient></defs><ellipse cx="160" cy="244" rx="103" ry="10" fill="#0a1c32"/><g class="training-body"><path class="training-legs" d="M130 200v33m62-33v33" stroke="#92b4c9" stroke-width="21"/><path d="M110 235h36m29 0h36" stroke="#d8f6ec" stroke-width="13" stroke-linecap="round"/><path d="M104 140 80 179" stroke="#86bcc6" stroke-width="20" stroke-linecap="round"/><g class="training-arm"><path d="m215 140 27 32 32-16" fill="none" stroke="#b7e2de" stroke-width="20" stroke-linecap="round"/><circle cx="278" cy="153" r="12" fill="#e0f5dc"/></g><rect x="110" y="123" width="100" height="84" rx="18" fill="url(#training-metal)" stroke="#b7e1e5" stroke-width="4"/><rect x="128" y="141" width="64" height="42" rx="9" fill="#17364d"/><text x="160" y="171" text-anchor="middle" font-size="27" fill="${good?'#a8ffd8':'#ffdc95'}">${good?'✓':'?'}</text><path d="M160 47V27" stroke="#9fd6d9" stroke-width="5"/><circle class="robot-antenna" cx="160" cy="22" r="9" fill="${good?'#a2ffcd':'#ffda88'}"/><rect x="101" y="48" width="118" height="76" rx="25" fill="url(#training-metal)" stroke="#e0fff0" stroke-width="4"/><rect x="114" y="64" width="92" height="44" rx="15" fill="#163047"/><g class="training-eyes" fill="#a7ffd6"><ellipse cx="136" cy="83" rx="7" ry="9"/><ellipse cx="185" cy="83" rx="7" ry="9"/></g><path d="M148 96q12 ${good?10:-6} 24 0" stroke="#a7ffd6" stroke-width="3" fill="none"/></g></svg><div class="delivery-item" aria-label="${good?cue.wanted:cue.wrong}">${foodIcon(good?cue.wanted:cue.wrong)}</div><div class="lab-conveyor"></div>${win?'<div class="helper-badge">★ CERTIFIED HELPER</div>':''}</div><div class="training-status"><span>MISSION: COMPLETE THE DELIVERY</span><b>${Math.min(progress,target)} / ${target}</b><div class="training-cells">${Array.from({length:target},(_,i)=>`<i class="${i<progress?'on':''}"></i>`).join('')}</div><div class="robot-systems">${['EYES','ARMS','DELIVERY'].map((name,i)=>`<span class="${systems[i]?'online':''}">${systems[i]?'✓':'○'} ${name}</span>`).join('')}</div><p>${objective}</p></div></section>`;
}

export const ROBOT_FINALE_MS=6500;
export function robotFinale(cue:RobotCue,win:boolean,elapsed:number,calm:boolean){
 const art=trainingRobot(cue,win?'win':'loss',win?7:0,7).match(/<svg[\s\S]*?<\/svg>/)?.[0]||'';
 return `<main class="robot-finale ${win?'delivery-win':'delivery-loss'}" style="--elapsed:${elapsed/1000}s" data-calm="${calm}"><div class="delivery-heading"><p>FINAL MISSION</p><h1>${win?'Deliver the order!':'Delivery interrupted'}</h1><span>${win?'Recognize → Pick up → Deliver':'The robot needs more power to reach the customer.'}</span></div><div class="delivery-stage"><div class="dispatch-station">ROBOT LAB</div><div class="delivery-road"></div><div class="delivery-traveller">${art}<span class="travelling-food">${foodIcon(cue.wanted)}</span></div><div class="delivery-customer"><span class="customer-face">☺</span><div class="customer-counter">CUSTOMER</div><span class="received-food">${foodIcon(cue.wanted)}</span><b>THANK YOU!</b></div><div class="delivery-report">${win?'★ DELIVERY COMPLETE!':'POWER LOST · MISSION FAILED'}</div></div><p class="finale-explain">${win?'Your instructions made this possible.':'The customer is still waiting. Try the mission again!'}</p></main>`;
}
