/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlayBombRouteImport } from './routes/play.bomb'
import { Route as PlayDemoRouteImport } from './routes/play.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBombRoute = PlayBombRouteImport.update({
  id: '/play/bomb',
  path: '/play/bomb',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDemoRoute = PlayDemoRouteImport.update({
  id: '/play/demo',
  path: '/play/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/results' | '/settings' | '/setup' | '/play/bomb' | '/play/demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/results' | '/settings' | '/setup' | '/play/bomb' | '/play/demo'
  id:
    | '__root__'
    | '/'
    | '/results'
    | '/settings'
    | '/setup'
    | '/play/bomb'
    | '/play/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  PlayBombRoute: typeof PlayBombRoute
  PlayDemoRoute: typeof PlayDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bomb': {
      id: '/play/bomb'
      path: '/play/bomb'
      fullPath: '/play/bomb'
      preLoaderRoute: typeof PlayBombRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/demo': {
      id: '/play/demo'
      path: '/play/demo'
      fullPath: '/play/demo'
      preLoaderRoute: typeof PlayDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  PlayBombRoute: PlayBombRoute,
  PlayDemoRoute: PlayDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
