/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as PlayBombRouteImport } from './routes/play.bomb'
import { Route as PlayDemoRouteImport } from './routes/play.demo'
import { Route as PlayDetectiveRouteImport } from './routes/play.detective'
import { Route as PlayMissionRouteImport } from './routes/play.mission'
import { Route as PlayRocketRouteImport } from './routes/play.rocket'
import { Route as PlaySentenceRouteImport } from './routes/play.sentence'
import { Route as PlaySpotlightRouteImport } from './routes/play.spotlight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBombRoute = PlayBombRouteImport.update({
  id: '/play/bomb',
  path: '/play/bomb',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDemoRoute = PlayDemoRouteImport.update({
  id: '/play/demo',
  path: '/play/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDetectiveRoute = PlayDetectiveRouteImport.update({
  id: '/play/detective',
  path: '/play/detective',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMissionRoute = PlayMissionRouteImport.update({
  id: '/play/mission',
  path: '/play/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRocketRoute = PlayRocketRouteImport.update({
  id: '/play/rocket',
  path: '/play/rocket',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySentenceRoute = PlaySentenceRouteImport.update({
  id: '/play/sentence',
  path: '/play/sentence',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySpotlightRoute = PlaySpotlightRouteImport.update({
  id: '/play/spotlight',
  path: '/play/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/mission': typeof PlayMissionRoute
  '/play/rocket': typeof PlayRocketRoute
  '/play/sentence': typeof PlaySentenceRoute
  '/play/spotlight': typeof PlaySpotlightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/mission': typeof PlayMissionRoute
  '/play/rocket': typeof PlayRocketRoute
  '/play/sentence': typeof PlaySentenceRoute
  '/play/spotlight': typeof PlaySpotlightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/bomb': typeof PlayBombRoute
  '/play/demo': typeof PlayDemoRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/mission': typeof PlayMissionRoute
  '/play/rocket': typeof PlayRocketRoute
  '/play/sentence': typeof PlaySentenceRoute
  '/play/spotlight': typeof PlaySpotlightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/results'
    | '/settings'
    | '/setup'
    | '/lesson/$lessonId'
    | '/play/bomb'
    | '/play/demo'
    | '/play/detective'
    | '/play/mission'
    | '/play/rocket'
    | '/play/sentence'
    | '/play/spotlight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/results'
    | '/settings'
    | '/setup'
    | '/lesson/$lessonId'
    | '/play/bomb'
    | '/play/demo'
    | '/play/detective'
    | '/play/mission'
    | '/play/rocket'
    | '/play/sentence'
    | '/play/spotlight'
  id:
    | '__root__'
    | '/'
    | '/results'
    | '/settings'
    | '/setup'
    | '/lesson/$lessonId'
    | '/play/bomb'
    | '/play/demo'
    | '/play/detective'
    | '/play/mission'
    | '/play/rocket'
    | '/play/sentence'
    | '/play/spotlight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  PlayBombRoute: typeof PlayBombRoute
  PlayDemoRoute: typeof PlayDemoRoute
  PlayDetectiveRoute: typeof PlayDetectiveRoute
  PlayMissionRoute: typeof PlayMissionRoute
  PlayRocketRoute: typeof PlayRocketRoute
  PlaySentenceRoute: typeof PlaySentenceRoute
  PlaySpotlightRoute: typeof PlaySpotlightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bomb': {
      id: '/play/bomb'
      path: '/play/bomb'
      fullPath: '/play/bomb'
      preLoaderRoute: typeof PlayBombRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/demo': {
      id: '/play/demo'
      path: '/play/demo'
      fullPath: '/play/demo'
      preLoaderRoute: typeof PlayDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/detective': {
      id: '/play/detective'
      path: '/play/detective'
      fullPath: '/play/detective'
      preLoaderRoute: typeof PlayDetectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/mission': {
      id: '/play/mission'
      path: '/play/mission'
      fullPath: '/play/mission'
      preLoaderRoute: typeof PlayMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/rocket': {
      id: '/play/rocket'
      path: '/play/rocket'
      fullPath: '/play/rocket'
      preLoaderRoute: typeof PlayRocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/sentence': {
      id: '/play/sentence'
      path: '/play/sentence'
      fullPath: '/play/sentence'
      preLoaderRoute: typeof PlaySentenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/spotlight': {
      id: '/play/spotlight'
      path: '/play/spotlight'
      fullPath: '/play/spotlight'
      preLoaderRoute: typeof PlaySpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  PlayBombRoute: PlayBombRoute,
  PlayDemoRoute: PlayDemoRoute,
  PlayDetectiveRoute: PlayDetectiveRoute,
  PlayMissionRoute: PlayMissionRoute,
  PlayRocketRoute: PlayRocketRoute,
  PlaySentenceRoute: PlaySentenceRoute,
  PlaySpotlightRoute: PlaySpotlightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
